#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: one stage() per step. Bootstrap order: npm will not link a trusted
# publisher to a package that does not exist yet, and a local publish carries
# no provenance. So a 0.0.0 placeholder reserves the name, the trusted
# publisher is linked to release.yml, and the v0.1.0 tag publishes with
# provenance from CI.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

REPO_SLUG=$(git remote get-url origin 2>/dev/null | sed -E 's#^(https://github.com/|git@github.com:)##; s#\.git$##' || true)
REPO_OWNER="${REPO_SLUG%%/*}"
REPO_NAME="${REPO_SLUG##*/}"

banner "npm setup for @agentarium/cli"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Preflight"
say "Checks the tools and the repository this wizard depends on."
if ! command -v npm >/dev/null 2>&1; then
  warn "npm is not installed; install Node 22.18+ first."
  exit 1
fi
say "npm $(npm --version), Node $(node --version 2>/dev/null || echo missing)"
say "GitHub repository: ${REPO_SLUG:-unknown (no origin remote)}"
if [[ "$REPO_SLUG" != "ducdv98/agentarium" ]]; then
  warn "origin is not ducdv98/agentarium; the trusted publisher must match the real repository."
fi
warn "The release workflow must be on origin/main before the tag is pushed (stage 6)."
pause "Press Enter if these look right."

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "npm account and two-factor"
say "npm publishing needs a logged-in account with 2FA turned on."
open_url "https://www.npmjs.com/login"
step "Sign in, or create an account if you have none."
step "Turn on two-factor authentication (account settings → Two-Factor Authentication)."
pause "Done with the browser? Press Enter to log in from this terminal."
npm login || warn "npm login did not finish; re-run this wizard once you are logged in."
say "Logged in as: $(npm whoami 2>/dev/null || echo 'not logged in')"
pause "Press Enter to continue."

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Create the @agentarium organisation"
say "The @agentarium scope must exist before any @agentarium/* package can be published."
open_url "https://www.npmjs.com/org/create"
step "Organisation name: agentarium"
step "Plan: Free (unlimited public packages)."
pause "Press Enter once the organisation exists."

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Reserve the package name"
say "Publishes a 0.0.0 placeholder so @agentarium/cli exists on npm."
say "The real 0.1.0 is published later by CI, with provenance."
note "This publishes a public placeholder. It is not removed by this wizard."
if confirm "Publish the 0.0.0 placeholder now?"; then
  PLACEHOLDER=$(mktemp -d)
  cat > "$PLACEHOLDER/package.json" <<'JSON'
{
  "name": "@agentarium/cli",
  "version": "0.0.0",
  "description": "Placeholder: name reserved for Agentarium. Real releases are published from CI.",
  "license": "MIT"
}
JSON
  (cd "$PLACEHOLDER" && npm publish --access public) && say "placeholder published" || warn "publish failed; fix the error above and re-run."
  rm -rf "$PLACEHOLDER"
else
  SKIPPED+=("placeholder publish of @agentarium/cli@0.0.0 (run stage 4 again)")
  warn "skipped; later stages need the package to exist."
fi
pause "Press Enter to continue."

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Link the trusted publisher"
say "Lets the release workflow publish without an npm token."
open_url "https://www.npmjs.com/package/@agentarium/cli/access"
step "Find 'Trusted Publisher' and choose GitHub Actions."
step "Organisation or user: ${REPO_OWNER:-ducdv98}"
step "Repository: ${REPO_NAME:-agentarium}"
step "Workflow filename: release.yml (the file name only, not the path)"
step "Environment: leave blank."
note "Field names may differ on the page; match them by meaning."
pause "Press Enter once you have saved the trusted publisher."

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Push main so the release workflow exists on GitHub"
say "Tags run the workflow file from the tagged commit, so main must have release.yml."
if [[ -n "$(git status --porcelain)" ]]; then
  warn "working tree has uncommitted changes; commit or stash them first."
  pause "Press Enter once the tree is clean."
fi
if confirm "Push main to origin now?"; then
  git push origin main && say "pushed main" || warn "push failed; fix it and re-run."
else
  SKIPPED+=("git push origin main")
fi
pause "Press Enter to continue."

# ── Stage 7 ───────────────────────────────────────────────────────────────
stage "Push the v0.1.0 tag"
say "Starts the release workflow: CI, then dry run, then publish with provenance."
note "Pushing a tag is hard to undo cleanly. Check the version in packages/cli is 0.1.0."
if confirm "Create and push tag v0.1.0 now?"; then
  if git tag v0.1.0 && git push origin v0.1.0; then
    say "tag v0.1.0 pushed"
  else
    warn "tag v0.1.0 was not pushed; check whether it already exists (git tag -l v0.1.0)."
  fi
  open_url "https://github.com/${REPO_SLUG:-ducdv98/agentarium}/actions"
  note "Watch the Release run. When it finishes, check @agentarium/cli@0.1.0 on npm shows a provenance badge."
else
  SKIPPED+=("tag v0.1.0 (git tag v0.1.0 && git push origin v0.1.0)")
fi

finish
